"""
📱 SOCIAL MEDIA PLATFORMS DATABASE
100+ platforms organized by size and type.
"""

# Tier 1: Major platforms (must have)
TIER_1_MAJOR = {
    "youtube": {
        "url": "https://accounts.google.com",
        "monthly_users": "2.5B",
        "type": "video",
        "best_for": "Long tutorials, reviews",
        "monetization": "AdSense, sponsorships",
        "signup_method": "Google account",
        "post_format": "Video 5-20min",
    },
    "facebook": {
        "url": "https://facebook.com",
        "monthly_users": "3B",
        "type": "mixed",
        "best_for": "Community, groups",
        "monetization": "Boosted posts, marketplace",
        "signup_method": "Email or phone",
        "post_format": "Mixed",
    },
    "instagram": {
        "url": "https://instagram.com",
        "monthly_users": "2B",
        "type": "visual",
        "best_for": "Reels, stories",
        "monetization": "Brand deals, affiliate",
        "signup_method": "Email or Facebook",
        "post_format": "Image/Reels",
    },
    "tiktok": {
        "url": "https://tiktok.com",
        "monthly_users": "1.5B",
        "type": "short_video",
        "best_for": "Viral short videos",
        "monetization": "Creator fund, brand deals",
        "signup_method": "Email or phone",
        "post_format": "15-60s video",
    },
    "x_twitter": {
        "url": "https://x.com",
        "monthly_users": "500M",
        "type": "microblog",
        "best_for": "News, threads, hot takes",
        "monetization": "Ads, premium",
        "signup_method": "Email or phone",
        "post_format": "Text + image",
    },
    "linkedin": {
        "url": "https://linkedin.com",
        "monthly_users": "1B",
        "type": "professional",
        "best_for": "B2B, thought leadership",
        "monetization": "Services, recruiting",
        "signup_method": "Email",
        "post_format": "Long text post",
    },
}

# Tier 2: Growing platforms
TIER_2_GROWING = {
    "pinterest": {"url": "https://pinterest.com", "users": "480M", "type": "visual"},
    "reddit": {"url": "https://reddit.com", "users": "430M", "type": "discussion"},
    "snapchat": {"url": "https://snapchat.com", "users": "750M", "type": "short_video"},
    "threads": {"url": "https://threads.net", "users": "200M", "type": "microblog"},
    "youtube_shorts": {"url": "https://youtube.com/shorts", "users": "2B", "type": "short_video"},
    "medium": {"url": "https://medium.com", "users": "100M", "type": "blog"},
    "substack": {"url": "https://substack.com", "users": "20M", "type": "newsletter"},
    "tumblr": {"url": "https://tumblr.com", "users": "135M", "type": "microblog"},
    "discord": {"url": "https://discord.com", "users": "150M", "type": "community"},
    "telegram": {"url": "https://telegram.org", "users": "800M", "type": "messaging"},
    "whatsapp": {"url": "https://whatsapp.com", "users": "2B", "type": "messaging"},
    "quora": {"url": "https://quora.com", "users": "300M", "type": "qa"},
    "twitch": {"url": "https://twitch.tv", "users": "140M", "type": "livestream"},
    "kick": {"url": "https://kick.com", "users": "50M", "type": "livestream"},
    "rumble": {"url": "https://rumble.com", "users": "80M", "type": "video"},
    "bitchute": {"url": "https://bitchute.com", "users": "20M", "type": "video"},
    "odysee": {"url": "https://odysee.com", "users": "10M", "type": "video"},
    "vk": {"url": "https://vk.com", "users": "100M", "type": "social"},
    "wechat": {"url": "https://wechat.com", "users": "1.3B", "type": "messaging"},
    "qq": {"url": "https://im.qq.com", "users": "600M", "type": "messaging"},
    "douyin": {"url": "https://douyin.com", "users": "750M", "type": "short_video"},
    "kuaishou": {"url": "https://kuaishou.com", "users": "600M", "type": "short_video"},
    "weibo": {"url": "https://weibo.com", "users": "580M", "type": "microblog"},
    "xiaohongshu": {"url": "https://xiaohongshu.com", "users": "200M", "type": "lifestyle"},
}

# Tier 3: Niche platforms
TIER_3_NICHE = {
    "Product Hunt": {"url": "https://producthunt.com", "users": "5M", "niche": "tech products"},
    "Hacker News": {"url": "https://news.ycombinator.com", "users": "5M", "niche": "tech/startup"},
    "Indie Hackers": {"url": "https://indiehackers.com", "users": "1M", "niche": "indie founders"},
    "Dev.to": {"url": "https://dev.to", "users": "1M", "niche": "developers"},
    "Hashnode": {"url": "https://hashnode.com", "users": "1M", "niche": "developers"},
    "Mastodon": {"url": "https://joinmastodon.org", "users": "10M", "niche": "decentralized"},
    "Bluesky": {"url": "https://bsky.app", "users": "5M", "niche": "decentralized"},
    "Lens Protocol": {"url": "https://lens.xyz", "users": "500K", "niche": "web3"},
    "Farcaster": {"url": "https://farcaster.xyz", "users": "200K", "niche": "web3"},
    "Mirror": {"url": "https://mirror.xyz", "users": "100K", "niche": "web3 writing"},
    "Cohost": {"url": "https://cohost.org", "users": "1M", "niche": "creative"},
    "Tumblr": {"url": "https://tumblr.com", "users": "135M", "niche": "creative"},
    "BeReal": {"url": "https://bereal.com", "users": "70M", "niche": "authentic"},
    "Gumroad": {"url": "https://gumroad.com", "users": "1M", "niche": "creators selling"},
    "Patreon": {"url": "https://patreon.com", "users": "8M", "niche": "membership"},
    "Ko-fi": {"url": "https://ko-fi.com", "users": "2M", "niche": "donations"},
    "Buy Me a Coffee": {"url": "https://buymeacoffee.com", "users": "2M", "niche": "donations"},
    "Drip": {"url": "https://drip.com", "users": "1M", "niche": "creators"},
    "Memberful": {"url": "https://memberful.com", "users": "1M", "niche": "membership"},
    "Ghost": {"url": "https://ghost.org", "users": "1M", "niche": "newsletters"},
    "Bento": {"url": "https://bento.me", "users": "500K", "niche": "link in bio"},
    "Linktree": {"url": "https://linktr.ee", "users": "50M", "niche": "link in bio"},
    "Beacons": {"url": "https://beacons.ai", "users": "5M", "niche": "link in bio"},
    "Stan Store": {"url": "https://stan.store", "users": "5M", "niche": "creator store"},
    "Gumlet": {"url": "https://gumlet.com", "users": "100K", "niche": "video hosting"},
    "Vimeo": {"url": "https://vimeo.com", "users": "200M", "niche": "video"},
    "Dailymotion": {"url": "https://dailymotion.com", "users": "100M", "niche": "video"},
    "Veoh": {"url": "https://veoh.com", "users": "30M", "niche": "video"},
    "Metacafe": {"url": "https://metacafe.com", "users": "20M", "niche": "video"},
    "PeerTube": {"url": "https://joinpeertube.org", "users": "500K", "niche": "decentralized video"},
    "Imgur": {"url": "https://imgur.com", "users": "200M", "niche": "images"},
    "Flickr": {"url": "https://flickr.com", "users": "60M", "niche": "photos"},
    "500px": {"url": "https://500px.com", "users": "10M", "niche": "photography"},
    "EyeEm": {"url": "https://eyeem.com", "users": "20M", "niche": "photography"},
    "VSCO": {"url": "https://vsco.co", "users": "100M", "niche": "photo editing"},
    "Behance": {"url": "https://behance.net", "users": "50M", "niche": "creative portfolio"},
    "Dribbble": {"url": "https://dribbble.com", "users": "10M", "niche": "design"},
    "DeviantArt": {"url": "https://deviantart.com", "users": "70M", "niche": "art"},
    "ArtStation": {"url": "https://artstation.com", "users": "20M", "niche": "art"},
    "Figma Community": {"url": "https://figma.com/community", "users": "5M", "niche": "design"},
    "Dribbble": {"url": "https://dribbble.com", "users": "10M", "niche": "design"},
    "CodePen": {"url": "https://codepen.io", "users": "2M", "niche": "front-end dev"},
    "GitHub": {"url": "https://github.com", "users": "100M", "niche": "code"},
    "GitLab": {"url": "https://gitlab.com", "users": "30M", "niche": "code"},
    "Bitbucket": {"url": "https://bitbucket.org", "users": "10M", "niche": "code"},
    "SourceForge": {"url": "https://sourceforge.net", "users": "5M", "niche": "code"},
    "Replit": {"url": "https://replit.com", "users": "20M", "niche": "code"},
    "CodeSandbox": {"url": "https://codesandbox.io", "users": "5M", "niche": "code"},
    "Stack Overflow": {"url": "https://stackoverflow.com", "users": "100M", "niche": "code Q&A"},
    "HackerEarth": {"url": "https://hackerearth.com", "users": "5M", "niche": "coding practice"},
    "Codeforces": {"url": "https://codeforces.com", "users": "2M", "niche": "competitive coding"},
    "LeetCode": {"url": "https://leetcode.com", "users": "10M", "niche": "coding interview"},
    "CodinGame": {"url": "https://codingame.com", "users": "5M", "niche": "coding games"},
    "Guru": {"url": "https://guru.com", "users": "1M", "niche": "freelance"},
    "Upwork": {"url": "https://upwork.com", "users": "20M", "niche": "freelance"},
    "Fiverr": {"url": "https://fiverr.com", "users": "5M", "niche": "freelance"},
    "Freelancer": {"url": "https://freelancer.com", "users": "50M", "niche": "freelance"},
    "Toptal": {"url": "https://toptal.com", "users": "1M", "niche": "freelance elite"},
    "99designs": {"url": "https://99designs.com", "users": "1M", "niche": "design freelance"},
    "Dribbble Jobs": {"url": "https://dribbble.com/jobs", "users": "1M", "niche": "design jobs"},
    "AngelList": {"url": "https://angellist.com", "users": "5M", "niche": "startup jobs"},
    "CrunchBoard": {"url": "https://crunchboard.com", "users": "1M", "niche": "tech jobs"},
    "Y Combinator": {"url": "https://ycombinator.com", "users": "5M", "niche": "startup accelerator"},
    "SlideShare": {"url": "https://slideshare.net", "users": "100M", "niche": "presentations"},
    "Scribd": {"url": "https://scribd.com", "users": "200M", "niche": "documents"},
    "Issuu": {"url": "https://issuu.com", "users": "100M", "niche": "publications"},
    "Pinterest": {"url": "https://pinterest.com", "users": "480M", "niche": "visual search"},
    "Mix": {"url": "https://mix.com", "users": "20M", "niche": "content curation"},
    "Flipboard": {"url": "https://flipboard.com", "users": "30M", "niche": "magazine"},
    "Wattpad": {"url": "https://wattpad.com", "users": "90M", "niche": "stories"},
    "Goodreads": {"url": "https://goodreads.com", "users": "90M", "niche": "books"},
    "Last.fm": {"url": "https://last.fm", "users": "50M", "niche": "music"},
    "Spotify": {"url": "https://spotify.com", "users": "500M", "niche": "music"},
    "SoundCloud": {"url": "https://soundcloud.com", "users": "200M", "niche": "music"},
    "Bandcamp": {"url": "https://bandcamp.com", "users": "10M", "niche": "indie music"},
    "Audiomack": {"url": "https://audiomack.com", "users": "20M", "niche": "music"},
    "Mixcloud": {"url": "https://mixcloud.com", "users": "20M", "niche": "DJ mixes"},
    "Anghami": {"url": "https://anghami.com", "users": "30M", "niche": "Arabic music"},
    "Gaana": {"url": "https://gaana.com", "users": "100M", "niche": "Indian music"},
    "JioSaavn": {"url": "https://jiosaavn.com", "users": "100M", "niche": "Indian music"},
    "Deezer": {"url": "https://deezer.com", "users": "20M", "niche": "music"},
    "Tidal": {"url": "https://tidal.com", "users": "5M", "niche": "hi-fi music"},
    "Pandora": {"url": "https://pandora.com", "users": "60M", "niche": "music"},
    "iHeartRadio": {"url": "https://iheart.com", "users": "100M", "niche": "music"},
    "TuneIn": {"url": "https://tunein.com", "users": "70M", "niche": "radio"},
    "iVoox": {"url": "https://ivoox.com", "users": "30M", "niche": "podcasts"},
    "Podimo": {"url": "https://podimo.com", "users": "5M", "niche": "podcasts"},
    "Podbean": {"url": "https://podbean.com", "users": "10M", "niche": "podcasting"},
    "Buzzsprout": {"url": "https://buzzsprout.com", "users": "1M", "niche": "podcasting"},
    "Transistor": {"url": "https://transistor.fm", "users": "100K", "niche": "podcasting"},
    "Anchor": {"url": "https://anchor.fm", "users": "5M", "niche": "podcasting"},
    "Spotify for Podcasters": {"url": "https://podcasters.spotify.com", "users": "5M", "niche": "podcasting"},
    "Apple Podcasts": {"url": "https://podcasts.apple.com", "users": "100M", "niche": "podcasting"},
    "Google Podcasts": {"url": "https://podcasts.google.com", "users": "50M", "niche": "podcasting"},
    "Stitcher": {"url": "https://stitcher.com", "users": "10M", "niche": "podcasting"},
    "iHeartPodcasts": {"url": "https://iheart.com/podcast", "users": "10M", "niche": "podcasting"},
    "TuneIn Podcasts": {"url": "https://tunein.com/podcasts", "users": "10M", "niche": "podcasting"},
}


# Daily trend research
TRENDING_NICHES_2026 = [
    "AI Tools & Prompts",
    "Personal Finance & Side Hustles",
    "Health & Longevity",
    "Remote Work & Digital Nomad",
    "Crypto & Web3",
    "Climate & Sustainability",
    "Mental Health & Wellness",
    "Skincare & Beauty",
    "Fitness & Weight Loss",
    "Education & Career",
    "Parenting & Family",
    "Travel & Experiences",
    "Food & Cooking",
    "Tech Reviews & Gadgets",
    "Fashion & Style",
    "Gaming & Esports",
    "Sports & Athletics",
    "Real Estate & Housing",
    "Investing & Stocks",
    "DIY & Crafts",
]

if __name__ == "__main__":
    total = len(TIER_1_MAJOR) + len(TIER_2_GROWING) + len(TIER_3_NICHE)
    print(f"📱 Total platforms in database: {total}")
    print(f"   Tier 1 (Major): {len(TIER_1_MAJOR)}")
    print(f"   Tier 2 (Growing): {len(TIER_2_GROWING)}")
    print(f"   Tier 3 (Niche): {len(TIER_3_NICHE)}")
    print(f"   Trending niches: {len(TRENDING_NICHES_2026)}")
